---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qa
  name: deployment-qa-wst-suite-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-qa-wst-suite-frontend
      env: qa
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-qa-wst-suite-frontend
        env: qa
    spec:
      containers:
      - image: 766440649995.dkr.ecr.us-east-1.amazonaws.com/wst-suite-frontend:latest
        imagePullPolicy: Always
        name: app-qa-wst-suite-frontend
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  namespace: qa
  name: service-qa-wst-suite-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-qa-wst-suite-frontend
    env: qa
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: qa
  name: ingress-qa-wst-suite-frontend
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: qagroup
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:766440649995:certificate/a2ee42ac-d200-42f7-ae34-fc80c65f832c
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - host: qawstsuite.wesportstech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-qa-wst-suite-frontend
                port:
                  number: 80